### ISSUE TITLE
Tkinter error blocks scrolling down (v12)

### ISSUE THREAD

**Issue by sormazabal** [JihwanMyung/LocoBox#2]
**Priority: Low**
When pressing the scroll bar the console logs the following error:

`Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/braintime/anaconda3/envs/locobox/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/braintime/anaconda3/envs/locobox/lib/python3.7/tkinter/__init__.py", line 1739, in yview
    res = self.tk.call(self._w, 'yview', *args)
_tkinter.TclError: unknown option "0": must be moveto or scroll`

However, schedules can still be set, so it does not affect overall functionality.

**Comment by sormazabal** [comment]
To do:
Test GUI layout and functionality on Windows, Ubuntu, and MacOS.

**Comment by sormazabal** [comment]
> **Priority: Low** When pressing the scroll bar the console logs the following error:
> 
> `Exception in Tkinter callback Traceback (most recent call last): File "/home/braintime/anaconda3/envs/locobox/lib/python3.7/tkinter/__init__.py", line 1705, in __call__ return self.func(*args) File "/home/braintime/anaconda3/envs/locobox/lib/python3.7/tkinter/__init__.py", line 1739, in yview res = self.tk.call(self._w, 'yview', *args) _tkinter.TclError: unknown option "0": must be moveto or scroll`
> 
> However, schedules can still be set, so it does not affect overall functionality.

FIXED: [in this commit](https://github.com/sormazabal/LocoBox/commit/1898014204e422aa14139c646e66357e97a80dff)
